kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodejs-openshift-example-git-v2
  namespace: teste2
  selfLink: /apis/apps/v1/namespaces/teste2/deployments/nodejs-openshift-example-git-v2
  uid: 2a8be721-94fd-496f-94ff-41cdc3623780
  resourceVersion: '279346780'
  generation: 8
  creationTimestamp: '2023-04-16T21:39:03Z'
  labels:
    app: nodejs-openshift-example-git-v2
    app.kubernetes.io/component: nodejs-openshift-example-git-v2
    app.kubernetes.io/instance: nodejs-openshift-example-git-v2
    app.kubernetes.io/name: nodejs
    app.kubernetes.io/part-of: sample-app
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 12-ubi7
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/MuriloFPC/nodejs-openshift-example.git'
    deployment.kubernetes.io/revision: '9'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"nodejs-openshift-example-git-v2:latest","namespace":"teste2"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nodejs-openshift-example-git-v2\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  managedFields:
    - manager: openshift-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-16T21:39:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:template':
            'f:spec':
              'f:containers':
                'k:{"name":"nodejs-openshift-example-git-v2"}':
                  'f:image': {}
    - manager: Mozilla
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-16T22:25:24Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:alpha.image.policy.openshift.io/resolve-names': {}
            'f:app.openshift.io/vcs-ref': {}
            'f:app.openshift.io/vcs-uri': {}
            'f:image.openshift.io/triggers': {}
            'f:openshift.io/generated-by': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:app.kubernetes.io/component': {}
            'f:app.kubernetes.io/instance': {}
            'f:app.kubernetes.io/name': {}
            'f:app.kubernetes.io/part-of': {}
            'f:app.openshift.io/runtime': {}
            'f:app.openshift.io/runtime-version': {}
        'f:spec':
          'f:progressDeadlineSeconds': {}
          'f:replicas': {}
          'f:revisionHistoryLimit': {}
          'f:selector':
            'f:matchLabels':
              .: {}
              'f:app': {}
          'f:strategy':
            'f:rollingUpdate':
              .: {}
              'f:maxSurge': {}
              'f:maxUnavailable': {}
            'f:type': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:deploymentconfig': {}
            'f:spec':
              'f:containers':
                'k:{"name":"nodejs-openshift-example-git-v2"}':
                  .: {}
                  'f:env':
                    .: {}
                    'k:{"name":"CHANCE_ERRO"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"MENSAGEM_TELA_INICIAL"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:imagePullPolicy': {}
                  'f:livenessProbe':
                    .: {}
                    'f:failureThreshold': {}
                    'f:httpGet':
                      .: {}
                      'f:path': {}
                      'f:port': {}
                      'f:scheme': {}
                    'f:initialDelaySeconds': {}
                    'f:periodSeconds': {}
                    'f:successThreshold': {}
                    'f:timeoutSeconds': {}
                  'f:name': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":8080,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:resources': {}
                  'f:terminationMessagePath': {}
                  'f:terminationMessagePolicy': {}
              'f:dnsPolicy': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:securityContext': {}
              'f:terminationGracePeriodSeconds': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-04-16T22:33:30Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:deployment.kubernetes.io/revision': {}
        'f:status':
          'f:availableReplicas': {}
          'f:collisionCount': {}
          'f:conditions':
            .: {}
            'k:{"type":"Available"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Progressing"}':
              .: {}
              'f:lastTransitionTime': {}
              'f:lastUpdateTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
          'f:updatedReplicas': {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-openshift-example-git-v2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-openshift-example-git-v2
        deploymentconfig: nodejs-openshift-example-git-v2
    spec:
      containers:
        - name: nodejs-openshift-example-git-v2
          image: >-
            murilofpc/nodejs-openshift-exemplo:v2
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MENSAGEM_TELA_INICIAL
              value: Essa mensagem está definada pelo ENV
            - name: CHANCE_ERRO
              value: '10'
          resources: {}
          livenessProbe:
            httpGet:
              path: /hc
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 8
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-04-16T21:50:40Z'
      lastTransitionTime: '2023-04-16T21:50:40Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-04-16T22:33:30Z'
      lastTransitionTime: '2023-04-16T21:39:03Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "nodejs-openshift-example-git-v2-75c4ff44d6" has successfully
        progressed.
  collisionCount: 1
